"""Export a spec to a standalone Dockerfile.

The export merges role package lists (from roles/<name>/defaults/main.yml)
with the referenced provision Dockerfile's directives. Docker-family only:
role defaults declare apt package names. Output is derived, never edited:
regenerate with `just dockerfile <name>`."""

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import vmf_lib as lib

BANNER = """\
# Generated by vmfactory from specs/{name}.yaml — do not edit.
# Regenerate: just dockerfile {name}
# Source of truth: the spec, roles/*/defaults/main.yml, and {dockerfile}.
"""


def canonical_ref(entry, ref, errors):
    """Pick the Docker ref for a pin: first matches entry with a tag."""
    for candidate in entry.get("matches") or []:
        if ":" in candidate:
            return candidate
    errors.append(f"error: images.yaml: pin {ref} has no tagged Docker ref in matches")
    return None


def role_packages(role):
    """Read vmf_packages from a role's defaults, or None."""
    defaults = lib.ROOT / "roles" / role / "defaults" / "main.yml"
    if not defaults.is_file():
        return None
    data = lib.load_yaml(defaults) or {}
    return data.get("vmf_packages") or []


def main():
    parser = argparse.ArgumentParser(
        description="Export a spec to a standalone Dockerfile"
    )
    parser.add_argument("spec", type=Path)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    errors = []
    spec = lib.load_yaml(args.spec)
    name = (spec or {}).get("name", "unknown")

    images = lib.load_yaml(lib.ROOT / "images.yaml")
    base_ref = (spec or {}).get("base")
    base = lib.resolve_base(base_ref, images, errors) if base_ref else None
    from_ref = canonical_ref(base, base_ref, errors) if base is not None else None
    if errors:
        for line in errors:
            print(line, file=sys.stderr)
        sys.exit(1)

    output = args.output or (lib.ROOT / "build" / name / "Dockerfile")
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        BANNER.format(name=name, dockerfile=spec.get("provision", {}).get("dockerfile", "<none>")),
        f"FROM {from_ref}",
        "",
    ]

    pkgs = []
    for role in spec.get("roles", []):
        got = role_packages(role)
        if got is None:
            lines.append(
                f"# note: role {role} has no defaults/main.yml vmf_packages; "
                "not included in this export"
            )
            continue
        pkgs.extend(got)
    if pkgs:
        lines.append("# platform packages (from roles)")
        lines.append(
            "RUN apt-get update "
            "&& apt-get install -y --no-install-recommends "
            + " ".join(pkgs)
            + " \\\n && rm -rf /var/lib/apt/lists/*"
        )
        lines.append("")

    provision = spec.get("provision")
    if provision:
        dockerfile = lib.ROOT / provision["dockerfile"]
        if not dockerfile.is_file():
            print(f"error: dockerfile {dockerfile} does not exist", file=sys.stderr)
            sys.exit(1)
        parsed = lib.parse_dockerfile(dockerfile, images)
        errors.extend(parsed["errors"])
        if parsed["base"] is not None and parsed["base"]["url"] != base["url"]:
            errors.append(
                f"error: spec {name}: dockerfile FROM {parsed['base_ref']} "
                f"resolves to a different pin than spec base {base_ref}"
            )
        if parsed["copies"]:
            errors.append(
                "error: export cannot carry COPY context; "
                "COPY sources resolve against the original Dockerfile's directory"
            )
        if errors:
            for line in errors:
                print(line, file=sys.stderr)
            sys.exit(1)

        body = [
            line
            for line in dockerfile.read_text(encoding="utf-8").splitlines()
            if not line.strip().upper().startswith("FROM ")
        ]
        lines.append(f"# tool content from {provision['dockerfile']}")
        lines.extend(body)
        lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")

    print(f"ok: exported {output}")
    print(f"    build with: docker build -f {output} .")


if __name__ == "__main__":
    main()
