"""Generate a Packer template, playbook, cloud-init seeds, and provision
script from a VM spec. Mirrors the AnyCTF factory: pinned base image,
Ansible provisioning, cloud-init cidata, runtime seed with static IP."""

import argparse
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import vmf_lib as lib

BUILD_PASSWORD = "vmf-build"

PACKER_TEMPLATE = """packer {{
  required_version = ">= 1.10.0"

  required_plugins {{
    qemu = {{
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/qemu"
    }}

    ansible = {{
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }}
  }}
}}

variable "base_image_url" {{
  type        = string
  default     = "{base_url}"
  description = "Pinned base image ({base_ref})"
}}

variable "base_image_checksum" {{
  type        = string
  default     = "{base_checksum}"
  description = "Checksum of the pinned image"
}}

variable "machine_name" {{
  type        = string
  default     = "{name}"
  description = "Name of the machine"
}}

source "qemu" "lab" {{
  accelerator      = "kvm"
  cpus             = {cpu}
  memory           = {memory}
  disk_size        = "{disk_size}"
  format           = "qcow2"
  disk_image       = true
  iso_url          = var.base_image_url
  iso_checksum     = var.base_image_checksum
  output_directory = "image"
  vm_name          = "vmf-{name}"
  headless         = true
  cd_files         = ["meta-data", "user-data"]
  cd_label         = "cidata"
  boot_wait        = "10s"
  ssh_username     = "{ssh_user}"
  ssh_password     = "{build_password}"
  ssh_timeout      = "30m"
  shutdown_command = "sudo shutdown -P now"
}}

build {{
  sources = ["source.qemu.lab"]

  provisioner "ansible" {{
    playbook_file    = "${{path.root}}/playbook.yml"
    user             = "{ssh_user}"
    use_sftp         = true
    ansible_env_vars = ["ANSIBLE_ROLES_PATH={roles_path}"]
  }}
{file_provisioners}
  provisioner "shell" {{
    script          = "${{path.root}}/provision.sh"
    execute_command = "sudo bash {{{{ .Path }}}}"
  }}
}}
"""

STAGE_DIR_PROVISIONER = """  provisioner "shell" {
    inline = ["mkdir -p /tmp/vmf-stage"]
  }
"""

FILE_PROVISIONER = """  provisioner "file" {{
    source      = "{src}"
    destination = "/tmp/vmf-stage/{index}"
  }}
"""


def emit_provision(path, parsed, copies_resolved):
    """Write provision.sh: translated ENV/COPY/RUN from the Dockerfile.

    Staged uploads live at flat paths /tmp/vmf-stage/<index> — Packer's file
    provisioner does not create missing multi-component destination parents
    (a dest like /tmp/a/b collapses into a file named /tmp/a), so every
    upload targets a simple filename under the existing /tmp directory.
    """
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by scripts/generate.py from a Dockerfile subset. Do not edit.",
        "set -euo pipefail",
        "",
        "source /etc/profile.d/vmf-pipx.sh 2>/dev/null || true",
    ]
    if parsed["envs"]:
        lines.append("# persist ENV for future shells (Dockerfile ENV semantics)")
        lines.append("cat > /etc/profile.d/vmf-env.sh <<'VMF_ENV_EOF'")
        lines.extend(f"export {k}={lib.shquote(v)}" for k, v in parsed["envs"])
        lines.append("VMF_ENV_EOF")
        lines.extend(f"export {k}={lib.shquote(v)}" for k, v in parsed["envs"])
        lines.append("")
    for index, (_, dest, is_dir) in enumerate(copies_resolved):
        upload = f"/tmp/vmf-stage/{index}"
        if is_dir:
            lines.append(f"mkdir -p {lib.shquote(dest)}")
            lines.append(f"cp -a {lib.shquote(upload + '/.')}/ {lib.shquote(dest)}/")
        else:
            lines.append(f"mkdir -p \"$(dirname {lib.shquote(dest)})\"")
            lines.append(f"cp -a {lib.shquote(upload)} {lib.shquote(dest)}")
    current_dir = None
    for run in parsed["runs"]:
        if run["dir"] != current_dir:
            lines.append(f"cd {lib.shquote(run['dir'] or '/')}")
            current_dir = run["dir"]
        lines.append(run["cmd"])
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    path.chmod(0o755)


def main():
    parser = argparse.ArgumentParser(
        description="Generate the Packer template, playbook, seeds, and provision script for a spec"
    )
    parser.add_argument("spec", type=Path)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    errors = []
    spec = lib.load_yaml(args.spec)
    for err in lib.schema_errors(spec, "spec.schema.json"):
        errors.append(f"error: spec {args.spec.name}: schema {lib.json_path(err)}: {err.message}")

    images = lib.load_yaml(lib.ROOT / "images.yaml")
    base = None
    spec = lib.load_yaml(args.spec)
    name = (spec or {}).get("name", "unknown")
    base_ref = (spec or {}).get("base")
    if base_ref:
        base = lib.resolve_base(base_ref, images, errors)

    if errors:
        for line in errors:
            print(line, file=sys.stderr)
        sys.exit(1)

    output = args.output or (lib.ROOT / "build" / name)
    output.mkdir(parents=True, exist_ok=True)

    roles = []
    for role in spec.get("roles", []):
        role_path = lib.ROOT / "roles" / role
        if not role_path.is_dir():
            errors.append(f"error: spec {args.spec.name}: role directory {role_path} does not exist")
        else:
            roles.append({"role": role})

    network = spec["network"]
    gateway = network.get("gateway", network["ip"].rsplit(".", 1)[0] + ".1")

    parsed = None
    if provision := spec.get("provision"):
        dockerfile = lib.ROOT / provision["dockerfile"]
        if not dockerfile.is_file():
            errors.append(f"error: spec {args.spec.name}: dockerfile {dockerfile} does not exist")
        else:
            parsed = lib.parse_dockerfile(dockerfile, images)
            errors.extend(parsed["errors"])
            if parsed["base"] is not None and parsed["base_ref"] != base_ref and \
               parsed["base"].get("url") != base.get("url"):
                errors.append(
                    f"error: spec {args.spec.name}: dockerfile FROM {parsed['base_ref']} "
                    f"resolves to a different pin than spec base {base_ref}"
                )

    if errors:
        for line in errors:
            print(line, file=sys.stderr)
        sys.exit(1)

    playbook = [
        {
            "hosts": "all",
            "become": True,
            "gather_facts": True,
            "vars": {"vmf_user": base["user"]},
            "roles": roles,
        }
    ]
    with open(output / "playbook.yml", "w", encoding="utf-8") as fh:
        yaml.safe_dump(playbook, fh, sort_keys=False, default_flow_style=False)

    with open(output / "user-data", "w", encoding="utf-8") as fh:
        fh.write(
            "#cloud-config\n"
            f"hostname: {name}\n"
            "ssh_pwauth: true\n"
            "chpasswd:\n"
            "  expire: false\n"
            "  users:\n"
            f"    - name: {base['user']}\n"
            f"      password: {BUILD_PASSWORD}\n"
            "      type: text\n"
        )
    with open(output / "meta-data", "w", encoding="utf-8") as fh:
        fh.write(f"instance-id: {name}\nlocal-hostname: {name}\n")

    disk_size = f"{spec.get('disk_gb', 10)}G"
    with open(output / "box.pkr.hcl", "w", encoding="utf-8") as fh:
        fh.write(
            PACKER_TEMPLATE.format(
                base_url=base["url"],
                base_checksum=base["checksum"],
                base_ref=base_ref,
                name=name,
                cpu=spec.get("cpu", 2),
                memory=spec.get("memory_gb", 4) * 1024,
                disk_size=disk_size,
                ssh_user=base["user"],
                build_password=BUILD_PASSWORD,
                roles_path=lib.ROOT / "roles",
                file_provisioners="",
            )
        )

    copies_resolved = []
    if parsed is not None:
        context = dockerfile.parent
        for index, copy in enumerate(parsed["copies"]):
            src = context / copy["src"]
            if not src.exists():
                errors.append(f"error: dockerfile: COPY source {src} does not exist")
                continue
            copies_resolved.append((src, copy["dest"], src.is_dir()))

    # Spec files: staged via file provisioners to /tmp/vmf-copy/N, installed
    # by provision.sh with explicit owner/group/mode.
    spec_files = []
    for offset, entry in enumerate(spec.get("files", [])):
        src = lib.ROOT / entry["src"]
        if not src.is_file():
            errors.append(f"error: spec {args.spec.name}: file src {src} does not exist")
            continue
        index = len(copies_resolved) + offset
        owner = entry.get("owner", "root")
        group = entry.get("group", owner)
        mode = entry.get("mode", "0644")
        spec_files.append((src, entry, index, owner, group, mode))

    if errors:
        for line in errors:
            print(line, file=sys.stderr)
        sys.exit(1)

    provision_path = output / "provision.sh"
    if parsed is not None:
        emit_provision(provision_path, parsed, copies_resolved)

    file_blocks = ""
    for index, (src, dest, is_dir) in enumerate(copies_resolved):
        file_blocks += FILE_PROVISIONER.format(src=str(src), index=index)
    for src, entry, index, owner, group, mode in spec_files:
        file_blocks += FILE_PROVISIONER.format(src=str(src), index=index)

    install_lines = []
    for src, entry, index, owner, group, mode in spec_files:
        upload = f"/tmp/vmf-stage/{index}"
        install_lines.append(f"mkdir -p \"$(dirname {lib.shquote(entry['dest'])})\"")
        install_lines.append(
            f"install -m {mode} -o {lib.shquote(owner)} -g {lib.shquote(group)} "
            f"{lib.shquote(upload)} {lib.shquote(entry['dest'])}"
        )

    if install_lines:
        if provision_path.exists():
            body = provision_path.read_text(encoding="utf-8").rstrip("\n")
            provision_path.write_text(
                body + "\n\n# files from the spec (owner/group/mode enforced)\n"
                + "\n".join(install_lines) + "\n",
                encoding="utf-8",
            )
        else:
            emit_provision(provision_path, {"envs": [], "runs": [], "copies": []}, [])
            body = provision_path.read_text(encoding="utf-8").rstrip("\n")
            provision_path.write_text(
                body + "\n\n# files from the spec (owner/group/mode enforced)\n"
                + "\n".join(install_lines) + "\n",
                encoding="utf-8",
            )

    # Staging dir must exist before uploads: Packer's file provisioner
    # mangles destinations whose parent directory is missing.
    if file_blocks:
        template = (output / "box.pkr.hcl").read_text(encoding="utf-8")
        template = template.replace(
            '  provisioner "shell"',
            STAGE_DIR_PROVISIONER + file_blocks + '  provisioner "shell"',
        )
        (output / "box.pkr.hcl").write_text(template, encoding="utf-8")

    with open(output / "vm.conf", "w", encoding="utf-8") as fh:
        fh.write(
            f"NAME={name}\n"
            f"SSH_USER={base['user']}\n"
            f"SSH_PASS={BUILD_PASSWORD}\n"
            f"IP={network['ip']}\n"
            f"GATEWAY={gateway}\n"
            f"CPU={spec.get('cpu', 2)}\n"
            f"MEM_MB={spec.get('memory_gb', 4) * 1024}\n"
            f"DISK=image/vmf-{name}\n"
            f"BOOT_ISO=boot-seed.iso\n"
        )

    boot_dir = output / "boot"
    boot_dir.mkdir(parents=True, exist_ok=True)
    (boot_dir / "meta-data").write_text(
        f"instance-id: {name}-boot\nlocal-hostname: {name}\n", encoding="utf-8"
    )
    boot_user_data = (output / "user-data").read_text(encoding="utf-8")
    if "docker" in spec.get("roles", []):
        boot_user_data += (
            "runcmd:\n"
            f"  - usermod -aG docker {base['user']}\n"
        )
    (boot_dir / "user-data").write_text(boot_user_data, encoding="utf-8")
    (boot_dir / "network-config").write_text(
        "version: 2\n"
        "ethernets:\n"
        "  nic:\n"
        "    match:\n"
        "      name: 'en*'\n"
        f"    addresses: [{network['ip']}/24]\n"
        "    routes:\n"
        "      - to: default\n"
        f"        via: {gateway}\n"
        "    nameservers:\n"
        "      addresses: [1.1.1.1]\n",
        encoding="utf-8",
    )
    seed = output / "boot-seed.iso"
    result = subprocess.run(
        [
            "xorriso", "-as", "mkisofs", "-o", str(seed), "-volid", "cidata",
            "-joliet", "-rock",
            str(boot_dir / "meta-data"),
            str(boot_dir / "user-data"),
            str(boot_dir / "network-config"),
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("error: boot seed ISO creation failed:", result.stderr.strip(), file=sys.stderr)
        sys.exit(1)

    for warning in (parsed or {}).get("warnings", []):
        print(f"warning: {warning}")
    print(f"ok: generated {output / 'playbook.yml'} with {len(roles)} roles")
    print(f"ok: generated {output / 'box.pkr.hcl'} with pinned source {base['url']}")
    print(f"ok: generated {output / 'user-data'} and {output / 'meta-data'}")
    if parsed is not None:
        print(f"ok: generated {output / 'provision.sh'} from {dockerfile.name}")
    print(f"ok: generated {seed} with static IP {network['ip']}")


if __name__ == "__main__":
    main()
